# proguard-rules.pro
# This file is copied to android/app/proguard-rules.pro by the build workflow
# (the android/ folder is generated by `expo prebuild`).
#
# R8/ProGuard rules for FridgeMemo. The default optimized ProGuard config
# (proguard-android-optimize.txt) is applied by Gradle; these rules keep the
# React Native + Expo runtime working under minification and resource shrinking.

# ---- React Native core ----
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.jni.** { *; }
-dontwarn com.facebook.react.**
-dontwarn com.facebook.hermes.**

# Keep JNI / native method bindings.
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep annotated React modules and methods used via reflection.
-keepclassmembers class * {
    @com.facebook.react.bridge.ReactMethod <methods>;
}
-keep @com.facebook.react.module.annotations.ReactModule class * { *; }

# ---- Expo ----
-keep class expo.modules.** { *; }
-dontwarn expo.modules.**

# ---- AsyncStorage ----
-keep class com.reactnativecommunity.asyncstorage.** { *; }

# ---- Misc safe defaults ----
-keepattributes *Annotation*, Signature, InnerClasses, EnclosingMethod
-dontwarn okio.**
-dontwarn javax.annotation.**
